### PR TITLE
Upgrade grunt-bower-task to 0.4.0

### PR DESCRIPTION
**Pull request by jandudulski**
Before:

``` bash
$ lineman grunt bower:install
Running "bower:install" (bower) task
Fatal error: Arguments to path.join must be strings
```

After:

``` bash
$ lineman grunt bower:install 
Running "bower:install" (bower) task
>> Installed bower packages

Done, without errors.
```

### CODE REVIEW

**Comment by searls** [comment]
Hey @jayharris can you sign off?

**Comment by jayharris** [comment]
:thumbsup: This is something we should have done a while ago. This brings us in line with current Bower.

We will need a version bump, and the engine should be listed and pushed to >= 0.10.0.

**Comment by searls** [comment]
Do you have push rights? I'm not at my machine

**Comment by jayharris** [comment]
For the version and engine? I do for GitHub, but not for NPM. But I'm not at my machine, either.
I can hit them in about an hour.

**Comment by searls** [comment]
I'll add you to npm ASAP then

**Comment by jayharris** [comment]
Pushed to NPM.

**Pull request merged**
